# -*- coding: utf-8 -*-
"""Take multiple numbers through input and print the sum of the numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7jCUdBo1QmRIFI3ivU4TeCI9yd7E9o1
"""

x= [int(i)for i in input("Enter integer value: ").split()]
print(sum(x))